### ISSUE TITLE
bug：nested body element in Element panel

### ISSUE THREAD

**Issue by hec9527** [Tencent/vConsole#399]
once we changed the body's property, vConsole will add nested body into body element
Reduce the performance and development experience.

below is a sample demo of this bug:
[codeSandbox](https://codesandbox.io/s/pedantic-night-othrr?file=/index.html:890-974)

**Comment by Maizify** [comment]
Thank you for spotting the problem. 

After furthe debuging, there is no need to limit `nodeName == 'BODY'`, all `onAttributesChange()` as well as `onCharacterDataChange()` changes should use `'replace'` as `renderMethod`.

So I push a new commit to fix it instead of using PR #400. Thanks a lot as well!
