### ISSUE TITLE
Unable to print HTML elements in the console

### ISSUE THREAD

**Issue by vamsitallam** [Tencent/vConsole#476]
vConsole Version:
3.9.5

Consider the below code,
```
HTML:

<!DOCTYPE html>
<html>
  <head> </head>
  <body>
   <h1 id="hello">Hello World</h1>
  </body>
</html>

JS:

let headingEl = document.getElementById("hello")
console.log(headingEl);
```

#### Expectation:
Here the expectation is to log the HTML heading element in the output as:
![image](https://user-images.githubusercontent.com/43596618/142142235-285de186-3106-4791-90f8-1f27a0b58570.png)

#### Current Output:
Instead of HTML element we are getting HTML element properties as shown below:

![image](https://user-images.githubusercontent.com/43596618/142142320-9dc49235-1cdb-4a7d-99bb-1ee162deb814.png)

Thanks for the wonderful product, it would be helpful if we can fix this error.

**Comment by Maizify** [comment]
Thank you for your feedback.

In what scenario do you need to view Element instead of Properties?

Considering the following factors, I originally set the output to Properties:

1. In the vConsole panel, we cannot highlight the corresponding Element on the page when selecting the output Element. I think this is a very convenient feature on Chrome devtools, but it is difficult to implement in vConsole.

2. In addition to the above purposes, the console.log(element) is generally used to view the content of the field, and it is reasonable to output properties at this time.

3. Maybe adding a "Reveal in Elements Panel" function can meet your needs. I'm currently using Svelte to rewrite the view layer. After the rewrite, I might be able to achieve this function better.

**Comment by isaacking5** [comment]
@Maizify Iam also experiencing same problem 

is the fix was released in the latest version ??

if not, let us know if you have any work around 

Thank you :handshake:
